import { ClerkProvider } from '@clerk/nextjs';
import '../globals.css';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Threads',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="ko">
        <body className="">
          {/* Topbar */}

          <main>
            {/* LeftSidebar */}
            <section className="main-container">
              <div className="w-full max-w-4xl">{children}</div>
            </section>
            {/* RightSidebar */}
          </main>

          {/* Bottombar */}
        </body>
      </html>
    </ClerkProvider>
  );
}
